AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  SaveHelloFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.saveHello
      Runtime: nodejs14.x
      CodeUri: ./hello
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GreetingsTable
      Environment:
        Variables:
          GREETINGS_TABLE: !Ref GreetingsTable
      Events:
        Api:
          Type: Api
          Properties: 
            Path: /hello
            Method: POST
  
  GetHelloFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.getHello
      Runtime: nodejs14.x
      CodeUri: ./hello
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GreetingsTable
      Environment:
        Variables:
          GREETINGS_TABLE: !Ref GreetingsTable
      Events:
        HelloAPI:
          Type: Api
          Properties:
            Path: /hello
            Method: GET


  GreetingsTable:
    Type: AWS::Serverless::SimpleTable

Outputs:
  MyApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
